Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: cantera in /cluster/home/abecer02/.local/lib/python3.8/site-packages (3.0.0)
Requirement already satisfied: numpy>=1.12.0 in /cluster/tufts/hpc/tools/anaconda/202105/lib/python3.8/site-packages (from cantera) (1.19.5)
Requirement already satisfied: packaging in /cluster/tufts/hpc/tools/anaconda/202105/lib/python3.8/site-packages (from cantera) (20.9)
Requirement already satisfied: ruamel.yaml>=0.15.34 in /cluster/home/abecer02/.local/lib/python3.8/site-packages (from cantera) (0.18.6)
Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in /cluster/home/abecer02/.local/lib/python3.8/site-packages (from ruamel.yaml>=0.15.34->cantera) (0.2.8)
Requirement already satisfied: pyparsing>=2.0.2 in /cluster/tufts/hpc/tools/anaconda/202105/lib/python3.8/site-packages (from packaging->cantera) (2.4.7)
WARNING: You are using pip version 21.3; however, version 24.0 is available.
You should consider upgrading via the '/cluster/tufts/hpc/tools/anaconda/202105/bin/python -m pip install --upgrade pip' command.
Runnning Cantera version: 3.0.0
Computed Ignition Delay: 4.149e-05 seconds. Took 1.09s to compute
Traceback (most recent call last):
  File "CanteraIDT.py", line 76, in <module>
    time_history.to_csv("time_history.csv")
  File "/cluster/home/abecer02/.local/lib/python3.8/site-packages/cantera/composite.py", line 698, in __getattr__
    raise AttributeError(
AttributeError: 'SolutionArray' object has no attribute 'to_csv'
